import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createEngine,puzzleFor,easternDate,streakFor,matchesPlayerName} from '../public/core.js';
const d=JSON.parse(readFileSync(new URL('../public/data/hockey.json',import.meta.url))),e=createEngine(d);const id=name=>Number(Object.entries(d.players).find(([p,v])=>v[0]===name)[0]);
test('historical, traded and false connections',()=>{assert.ok(e.evidence(id('Wayne Gretzky'),id('Mark Messier')).length);assert.ok(e.evidence(id('Claude Giroux'),id('Derick Brassard')).length);assert.equal(e.evidence(id('Sidney Crosby'),id('Auston Matthews')).length,0)});
test('shortest cross-era route has verified links',()=>{const p=e.shortest(id('Gordie Howe'),id('Connor Bedard'));assert.equal(p.length-1,4);p.slice(1).forEach((x,i)=>assert.ok(e.evidence(p[i],x).length));assert.deepEqual(e.shortest(p[0],p[0]),[p[0]])});
test('search tolerates accents',()=>assert.ok(e.search('jagr').some(p=>p.name.includes('Jarom'))));
test('all scheduled puzzles have truthful par',()=>{for(const [a,b,par] of d.puzzles){assert.ok(par>=3&&par<=5);assert.equal(e.shortest(a,b).length-1,par)}});
test('daily reset follows Eastern midnight',()=>{assert.equal(easternDate(new Date('2026-10-05T03:59:00Z')),'2026-10-04');assert.equal(easternDate(new Date('2026-10-05T04:00:00Z')),'2026-10-05');assert.deepEqual(puzzleFor(d,'2026-10-04'),puzzleFor(d,'2026-10-04'));assert.notDeepEqual(puzzleFor(d,'2026-10-04'),puzzleFor(d,'2026-10-05'))});
test('streak stays active until today is missed',()=>{const wins={'2026-10-03':true,'2026-10-04':true};assert.equal(streakFor(wins,'2026-10-04'),2);assert.equal(streakFor(wins,'2026-10-05'),2);assert.equal(streakFor(wins,'2026-10-06'),0)});
test('decades restrict actual connection seasons and searchable players',()=>{const modern=createEngine(d,[2020]),eighties=createEngine(d,[1980]),none=createEngine(d,[]);assert.equal(modern.evidence(id('Wayne Gretzky'),id('Mark Messier')).length,0);assert.ok(eighties.evidence(id('Wayne Gretzky'),id('Mark Messier')).length);assert.equal(modern.search('Wayne Gretzky').length,0);assert.equal(none.search('Crosby').length,0);assert.equal(none.shortest(id('Claude Giroux'),id('Connor McDavid')),null);for(const g of modern.evidence(id('Claude Giroux'),id('Derick Brassard')))assert.equal(Math.floor(Number(String(g[1]).slice(0,4))/10)*10,2020)});
test('team hints prove a next shortest link without player names',()=>{const a=id('Claude Giroux'),b=id('Connor McDavid'),path=e.shortest(a,b),teams=e.hintTeams(a,b);assert.ok(teams.length);assert.deepEqual(teams,[...new Set(e.evidence(a,path[1]).map(g=>g[0]))]);assert.deepEqual(e.hintTeams(a,a),[])});
test('curated daily schedule uses only notable endpoints and verified par',()=>{const schedule=JSON.parse(readFileSync(new URL('../public/data/daily-puzzles.json',import.meta.url)));const notable=new Set(schedule.notablePlayerIds);for(const [a,b,par] of schedule.puzzles){assert.ok(notable.has(a)&&notable.has(b));assert.equal(e.shortest(a,b).length-1,par);assert.ok(par>=2&&par<=4)}assert.notDeepEqual(puzzleFor({...d,dailySchedule:schedule},'2026-10-04'),puzzleFor(d,'2026-10-04'))});

test('all shortest routes exactly match every two-link bridge',()=>{const a=id('Claude Giroux'),b=id('Connor McDavid'),all=e.allShortest(a,b);assert.equal(all.distance,2);const expected=Object.keys(d.players).map(Number).filter(p=>p!==a&&p!==b&&e.evidence(a,p).length&&e.evidence(p,b).length);const routes=[...all.routes()];assert.equal(all.count,BigInt(expected.length));assert.deepEqual(routes.map(r=>r[1]).sort((a,b)=>a-b),expected.sort((a,b)=>a-b));assert.equal(new Set(routes.map(r=>r.join(','))).size,routes.length);for(const route of routes){assert.equal(route.length,3);assert.ok(e.evidence(route[0],route[1]).length);assert.ok(e.evidence(route[1],route[2]).length)}});
test('lazy answer count handles more routes than safe integer without truncation',()=>{const players={0:['Start'],111:['End']},groups=[];let previous=[0];for(let layer=0;layer<55;layer++){const current=[layer*2+1,layer*2+2];for(const p of current)players[p]=['Player '+p];for(const a of previous)for(const b of current)groups.push(['X',20202021,[a,b]]);previous=current}for(const a of previous)groups.push(['X',20202021,[a,111]]);const all=createEngine({players,groups}).allShortest(0,111);assert.equal(all.count,2n**55n);assert.equal(all.distance,56);const it=all.routes();assert.equal(it.next().value.length,57);assert.equal(it.next().value.length,57)});
test('all shortest answers obey decades and handle disconnected and identical endpoints',()=>{const modern=createEngine(d,[2020]);assert.equal(modern.allShortest(id('Wayne Gretzky'),id('Mark Messier')).count,0n);assert.deepEqual([...modern.allShortest(id('Wayne Gretzky'),id('Mark Messier')).routes()],[]);const a=id('Claude Giroux');assert.deepEqual([...e.allShortest(a,a).routes()],[[a]]);assert.equal(e.allShortest(a,a).count,1n);const all=modern.allShortest(a,id('Connor McDavid'));for(const route of all.routes())for(let i=1;i<route.length;i++)for(const g of modern.evidence(route[i-1],route[i]))assert.ok(g[1]>=20202021)});

test('Palffy search accepts his full given name, nickname, and accented spelling without bypassing eras',()=>{
 for(const query of ['Žigmund Palffy','Žigmund Pálffy','Zigmund Palffy','Ziggy Palffy','Palffy']){
  assert.deepEqual(e.search(query).map(p=>p.id),[8458540],query);assert.equal(matchesPlayerName(8458540,'Ziggy Palffy',query),true);
 }
 assert.deepEqual(createEngine(d,[2020]).search('Žigmund Palffy'),[]);assert.equal(matchesPlayerName(8458540,'Ziggy Palffy','Sidney Crosby'),false);
});
